version: '3'
services:
  core-sp:
    image: ghcr.io/fua26/core_sepasang_planner:latest
    container_name: core-sp
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - sp-networks

networks:
  sp-networks: