version: '3'
services:
  core-sp:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: core-sp
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - sp-networks

networks:
  sp-networks: