name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f prod.Dockerfile -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.ref }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }} --all-tags
